version: '3.8'

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
  bert:
    build: ./bert
  elasticsearch:
    image: elasticsearch:7.17.9
    ports:
      - '9200:9200'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.17.9
    ports:
      - '5601:5601'
volumes:
  es-data:
    driver: local